// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWItXyzMjWxst_x40MUTaxvL5RJs-BEU',
    appId: '1:687640863867:web:b1c2195320799a3c4daede',
    messagingSenderId: '687640863867',
    projectId: 'cookingmeal-70605',
    authDomain: 'cookingmeal-70605.firebaseapp.com',
    storageBucket: 'cookingmeal-70605.firebasestorage.app',
    measurementId: 'G-F5FCML7XEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17lstI0ZTn8WGmziJ_5lFs_lAU90hjKM',
    appId: '1:687640863867:android:bd9db6cd9eb6ad5e4daede',
    messagingSenderId: '687640863867',
    projectId: 'cookingmeal-70605',
    storageBucket: 'cookingmeal-70605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzuHOKb1IVE0UzdbdxSNwFlVwJoc2kCcc',
    appId: '1:687640863867:ios:84c0fcf3846d97bd4daede',
    messagingSenderId: '687640863867',
    projectId: 'cookingmeal-70605',
    storageBucket: 'cookingmeal-70605.firebasestorage.app',
    iosClientId: '687640863867-33bs4e7cl595pfcl6taud5vidnif449c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzuHOKb1IVE0UzdbdxSNwFlVwJoc2kCcc',
    appId: '1:687640863867:ios:84c0fcf3846d97bd4daede',
    messagingSenderId: '687640863867',
    projectId: 'cookingmeal-70605',
    storageBucket: 'cookingmeal-70605.firebasestorage.app',
    iosClientId: '687640863867-33bs4e7cl595pfcl6taud5vidnif449c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfWItXyzMjWxst_x40MUTaxvL5RJs-BEU',
    appId: '1:687640863867:web:7525d1febc38f8184daede',
    messagingSenderId: '687640863867',
    projectId: 'cookingmeal-70605',
    authDomain: 'cookingmeal-70605.firebaseapp.com',
    storageBucket: 'cookingmeal-70605.firebasestorage.app',
    measurementId: 'G-T9RJEJQYX5',
  );
}
