// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLj9p1B5Wir2dICIfj5gYMhzoobp0qs7o',
    appId: '1:485175607200:web:a9e57344405ae2f3936ec5',
    messagingSenderId: '485175607200',
    projectId: 'cookingapp-85090',
    authDomain: 'cookingapp-85090.firebaseapp.com',
    storageBucket: 'cookingapp-85090.firebasestorage.app',
    measurementId: 'G-MVWF4LGYH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExaiPPPilX5DpYBJMPO1Cwl45PE-V2Dc',
    appId: '1:485175607200:android:dff6b1cfe2a54fb0936ec5',
    messagingSenderId: '485175607200',
    projectId: 'cookingapp-85090',
    storageBucket: 'cookingapp-85090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKJ8FwPcLLJxijy3OxTrhLYKjKdX3B0k',
    appId: '1:485175607200:ios:2ef71b2922e0d46e936ec5',
    messagingSenderId: '485175607200',
    projectId: 'cookingapp-85090',
    storageBucket: 'cookingapp-85090.firebasestorage.app',
    androidClientId: '485175607200-4qufvbah4reitveg0t9j327hfh9p4cf5.apps.googleusercontent.com',
    iosClientId: '485175607200-655gen46n2gegmktj23hj4brooo7q1nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPKJ8FwPcLLJxijy3OxTrhLYKjKdX3B0k',
    appId: '1:485175607200:ios:2ef71b2922e0d46e936ec5',
    messagingSenderId: '485175607200',
    projectId: 'cookingapp-85090',
    storageBucket: 'cookingapp-85090.firebasestorage.app',
    androidClientId: '485175607200-4qufvbah4reitveg0t9j327hfh9p4cf5.apps.googleusercontent.com',
    iosClientId: '485175607200-655gen46n2gegmktj23hj4brooo7q1nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLj9p1B5Wir2dICIfj5gYMhzoobp0qs7o',
    appId: '1:485175607200:web:a27c1ddd12acdb61936ec5',
    messagingSenderId: '485175607200',
    projectId: 'cookingapp-85090',
    authDomain: 'cookingapp-85090.firebaseapp.com',
    storageBucket: 'cookingapp-85090.firebasestorage.app',
    measurementId: 'G-S7KV0N9QXG',
  );

}